# Generated by Django 4.2.7 on 2024-02-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymodel', '0003_myusermodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUserModel',
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
